# Describes the targets run in continuous integration environment.
#
# Flutter infra uses this file to generate a checklist of tasks to be performed
# for every commit.
#
# More information at:
#  * https://github.com/flutter/cocoon/blob/main/CI_YAML.md
enabled_branches:
  - main
  - master

platform_properties:
  linux:
    properties:
      fuchsia_ctl_version: ""
      os: Linux

targets:
  - name: Linux fuchsia_ctl
    postsubmit: false
    recipe: fuchsia_ctl
    timeout: 90
    properties:
      add_recipes_cq: "true"
    scheduler: luci

  - name: Linux ci_yaml packages roller
    bringup: true
    recipe: infra/ci_yaml
    scheduler: luci
