# Describes the targets run in continuous integration environment.
#
# Flutter infra uses this file to generate a checklist of tasks to be performed
# for every commit.
#
# More information at:
#  * https://github.com/flutter/cocoon/blob/main/CI_YAML.md
enabled_branches:
  - main

platform_properties:
  linux:
    properties:
      os: Linux
  windows:
    properties:
      dependencies: >
        [
          {"dependency": "certs", "version": "version:9563bb"}
        ]
      device_type: none
      os: Windows
  mac_arm64:
    properties:
      dependencies: >-
        [
          {"dependency": "xcode", "version": "14a5294e"},
          {"dependency": "gems", "version": "v3.3.14"}
        ]
      os: Mac-12
      device_type: none
      cpu: arm64
      xcode: 14a5294e # xcode 14.0 beta 5
  mac_x64:
    properties:
      dependencies: >-
        [
          {"dependency": "xcode", "version": "14a5294e"},
          {"dependency": "gems", "version": "v3.3.14"}
        ]
      os: Mac-12
      device_type: none
      cpu: x86
      xcode: 14a5294e # xcode 14.0 beta 5

targets:
  ### iOS tasks ###
  # TODO(stuartmorgan): Switch ios_build_all_packages to Intel once the
  # iOS platform tests are brough up on ARM, to give build coverage on
  # both host architectures.
  - name: Mac_arm64 ios_build_all_packages master
    recipe: packages/packages
    timeout: 30
    properties:
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: ios_build_all_packages.yaml
      channel: master

  - name: Mac_arm64 ios_build_all_packages stable
    recipe: packages/packages
    timeout: 30
    properties:
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: ios_build_all_packages.yaml
      channel: stable

  - name: Mac_arm64 ios_platform_tests_shard_1 master
    bringup: true # New task
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 0 --shardCount 5"

  - name: Mac_arm64 ios_platform_tests_shard_2 master
    bringup: true # New task
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 1 --shardCount 5"

  - name: Mac_arm64 ios_platform_tests_shard_3 master
    bringup: true # New task
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 2 --shardCount 5"

  - name: Mac_arm64 ios_platform_tests_shard_4 master
    bringup: true # New task
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 3 --shardCount 5"

  - name: Mac_arm64 ios_platform_tests_shard_5 master
    bringup: true # New task
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 4 --shardCount 5"

  # Don't run full platform tests on both channels in pre-submit.
  - name: Mac_arm64 ios_platform_tests_shard_1 stable
    bringup: true # New task
    recipe: packages/packages
    presubmit: false
    timeout: 60
    properties:
      channel: stable
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 0 --shardCount 5"

  - name: Mac_arm64 ios_platform_tests_shard_2 stable
    bringup: true # New task
    recipe: packages/packages
    presubmit: false
    timeout: 60
    properties:
      channel: stable
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 1 --shardCount 5"

  - name: Mac_arm64 ios_platform_tests_shard_3 stable
    bringup: true # New task
    recipe: packages/packages
    presubmit: false
    timeout: 60
    properties:
      channel: stable
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 2 --shardCount 5"

  - name: Mac_arm64 ios_platform_tests_shard_4 stable
    bringup: true # New task
    recipe: packages/packages
    presubmit: false
    timeout: 60
    properties:
      channel: stable
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 3 --shardCount 5"

  - name: Mac_arm64 ios_platform_tests_shard_5 stable
    bringup: true # New task
    recipe: packages/packages
    presubmit: false
    timeout: 60
    properties:
      channel: stable
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: ios_platform_tests.yaml
      package_sharding: "--shardIndex 4 --shardCount 5"

  ### macOS desktop tasks ###
  # macos-platform_tests builds all the packages on ARM, so this build is run
  # on Intel to give us build coverage of both host types.
  - name: Mac_x64 build_all_packages master
    recipe: packages/packages
    timeout: 30
    properties:
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: mac_build_all_packages.yaml
      channel: master

  - name: Mac_x64 build_all_packages stable
    recipe: packages/packages
    timeout: 30
    properties:
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: mac_build_all_packages.yaml
      channel: stable

  # TODO(stuartmorgan): Remove "- packages" from all task names once
  # flutter/plugins is merged into this repo and turned down; it's here only
  # because names must be unique across all flutter repositories.
  - name: Mac_arm64 macos_platform_tests master - packages
    bringup: true # New task
    recipe: packages/packages
    timeout: 60
    properties:
      channel: master
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: macos_platform_tests.yaml

  - name: Mac_arm64 macos_platform_tests stable - packages
    bringup: true # New task
    recipe: packages/packages
    presubmit: false
    timeout: 60
    properties:
      channel: stable
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: macos_platform_tests.yaml

  - name: Mac_arm64 custom_package_tests master
    bringup: true # New configuration
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      version_file: flutter_master.version
      target_file: mac_custom_package_tests.yaml
      channel: master

  - name: Mac_arm64 custom_package_tests stable
    bringup: true # New configuration
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      version_file: flutter_stable.version
      target_file: mac_custom_package_tests.yaml
      channel: stable

  ### Windows desktop tasks ###
  - name: Windows custom_package_tests master - packages
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      target_file: windows_custom_package_tests.yaml
      channel: master
      version_file: flutter_master.version
      dependencies: >
        [
          {"dependency": "vs_build", "version": "version:vs2019"}
        ]

  - name: Windows dart_unit_tests master - packages
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      target_file: windows_dart_unit_tests.yaml
      channel: master
      version_file: flutter_master.version
      dependencies: >
        [
          {"dependency": "vs_build", "version": "version:vs2019"},
          {"dependency": "open_jdk", "version": "version:11"}
        ]

  - name: Windows win32-platform_tests master - packages
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      target_file: windows_build_and_platform_tests.yaml
      channel: master
      version_file: flutter_master.version
      dependencies: >
        [
          {"dependency": "vs_build", "version": "version:vs2019"}
        ]

  - name: Windows win32-platform_tests stable - packages
    recipe: packages/packages
    timeout: 60
    properties:
      add_recipes_cq: "true"
      target_file: windows_build_and_platform_tests.yaml
      channel: stable
      version_file: flutter_stable.version
      dependencies: >
        [
          {"dependency": "vs_build", "version": "version:vs2019"}
        ]

  - name: Windows windows-build_all_packages master
    recipe: packages/packages
    timeout: 30
    properties:
      add_recipes_cq: "true"
      target_file: windows_build_all_packages.yaml
      channel: master
      version_file: flutter_master.version
      dependencies: >
        [
          {"dependency": "vs_build", "version": "version:vs2019"}
        ]

  - name: Windows windows-build_all_packages stable
    recipe: packages/packages
    timeout: 30
    properties:
      add_recipes_cq: "true"
      target_file: windows_build_all_packages.yaml
      channel: stable
      version_file: flutter_stable.version
      dependencies: >
        [
          {"dependency": "vs_build", "version": "version:vs2019"}
        ]

  - name: Linux ci_yaml packages roller
    recipe: infra/ci_yaml
    timeout: 30
    runIf:
      - .ci.yaml
