name: Checks

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Run common checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make all scripts executable
        run: find .ci/scripts -type f -name "*.sh" -exec chmod +x {} \;
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build curl libgtk-3-dev libglib2.0-dev libgdk-pixbuf2.0-dev
      - name: prepare tool
        run: .ci/scripts/prepare_tool.sh
      - name: download Dart dependencies
        run: .ci/scripts/tool_runner.sh fetch-deps
      - name: Analyze
        run: dart ./script/tool/bin/flutter_plugin_tools.dart analyze
      - name: tool format
        run: .ci/scripts/plugin_tools_format.sh
      - name: format
        run: dart ./script/tool/bin/flutter_plugin_tools.dart format --fail-on-change --no-swift
      - name: Dart unit tests
        run: dart ./script/tool/bin/flutter_plugin_tools.dart dart-test 